matrix:
  include:
    - language: php
      php:
        - 7.1
        - 7.2
        - 7.3
      install: composer install
      script: vendor/bin/phpunit
      sudo: required
      dist: precise
    - language: node_js
      node:
        - 12
      install: npm install
      script: npm test

notifications:
  email:
    on_success: never
    on_failure: change
