matrix:
  include:
    - language: php
      php: 7.1
      install: make vendor
      script: make test-php
      sudo: required
      dist: precise
    - language: php
      php: 7.2
      install: make vendor
      script: make test-php
      sudo: required
      dist: precise
    - language: php
      php: 7.3
      install: make vendor
      script: make test-php
      sudo: required
      dist: precise
    - language: node_js
      node:
        - 12
      install: make node_modules
      script:
        - make build
        - make test-js

notifications:
  email:
    on_success: never
    on_failure: change
